---
title: "SOC612_l2"
author: "Raphi Duerr"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##### SOC612: Data Analytics for the Social Sciences - Solutions
##### Date: September 22, 2026
##### Author: R. Duerr
##### Task 2: Descriptive and exploratory analysis

1. 

```{r task2_1, echo=FALSE}

library(readr)
library(tidyverse)

setwd(getwd())
nhis22 <- read_csv("nhis-22.csv")

```

2. 

```{r task2_2, echo=FALSE}

fries.mean <- round(mean(nhis22$fries),2)
fries.median <- round(median(nhis22$fries),2)
fries.sd <- round(sd(nhis22$fries),2)
fries.range <- round(range(nhis22$fries),2)

potato.mean <- round(mean(nhis22$potato),2)
potato.median <- round(median(nhis22$potato),2)
potato.sd <- round(sd(nhis22$potato),2)
potato.range <- round(range(nhis22$potato),2)

beans.mean <- round(mean(nhis22$beans),2)
beans.median <- round(median(nhis22$beans),2)
beans.sd <- round(sd(nhis22$beans),2)
beans.range <- round(range(nhis22$beans),2)

pizza.mean <- round(mean(nhis22$pizza),2)
pizza.median <- round(median(nhis22$pizza),2)
pizza.sd <- round(sd(nhis22$pizza),2)
pizza.range <- round(range(nhis22$pizza),2)

variable <- c("mean", "median", "sd", "min", "max")
fries <- c(fries.mean, fries.median, fries.sd, fries.range)
potato <- c(potato.mean, potato.median, potato.sd, potato.range)
beans <- c(beans.mean, beans.median, beans.sd, beans.range)
pizza <- c(pizza.mean, pizza.median, pizza.sd, pizza.range)

eating_habits <- rbind(variable, fries, potato, beans, pizza)

```

3. 

```{r task2_3, echo=FALSE}

#fruit
plot(hist(nhis22$fruit, breaks = 60),
     main = "Histogram", xlab = "Fruit", ylab = "Freq.", col ="lightgreen", lwd=2)

ggplot(nhis22, aes(x = fruit)) +
  geom_histogram(bins = 60, fill = "lightgreen", color = "black") +
  labs(title = "Histogram", x = "Fruit", y = "Freq.") +
  theme_minimal()

#veggie
male_veggie <- nhis22$veggie[nhis22$gender == "male"]
female_veggie <- nhis22$veggie[nhis22$gender == "female"]

plot(density(male_veggie),
     main = "Density Plot of Veggie by Gender",
     xlab = "Veggie",
     ylab = "Dens.",
     col = "orange",
     lwd = 2,
     xlim = range(c(male_veggie, female_veggie)),
     ylim = c(0, max(density(male_veggie)$y, density(female_veggie)$y)))
lines(density(female_veggie), col = "purple", lwd = 2)
legend("topright",
       legend = c("Male", "Female"),
       col = c("orange", "purple"),
       lwd = 2)

ggplot(nhis22, aes(x = veggie, fill = gender)) +
  geom_density(alpha = 0.5) +
  labs(title = "Density Plot of Veggie by Gender",
       x = "Veggie",
       y = "Dens.") +
  theme_minimal()

#salad
boxplot(salad ~ educ,
        data = nhis22,
        main = "Boxplot of Veggie by Education",
        ylab = "Veggie",
        col = c("cyan", "beige","grey","brown"),
        border = "black")

ggplot(nhis22, aes(x = educ, y = veggie, fill = educ)) +
  geom_boxplot() +
  labs(title = "Boxplot of Veggie by Education",
       x = "Education",
       y = "Veggie") +
  theme_minimal()

```

4.

```{r task2_4, echo=FALSE}

library(magrittr)
library(tidyverse)

nhis22 <- nhis22 %>%
  mutate(coffee.cat = case_when(
      coffee %in% c(0) ~ "never",
      coffee %in% c(1:3) ~ "rarely",
      coffee %in% c(4:10) ~ "sometimes",
      coffee %in% c(11:20) ~ "regularly",
      coffee %in% c(21:29) ~ "often",
      coffee %in% c(30) ~ "daily",
      coffee %in% c(31:max(coffee)) ~ "daily+",
      TRUE ~ NA_character_)) %>%
  mutate(coffee.cat = factor(coffee.cat,
                     levels = c("never","rarely","sometimes","regularly",
                                "often","daily","daily+")))

nhis22 <- nhis22 %>%
  mutate(soda.cat = case_when(
      soda %in% c(0) ~ "never",
      soda %in% c(1:3) ~ "rarely",
      soda %in% c(4:10) ~ "sometimes",
      soda %in% c(11:20) ~ "regularly",
      soda %in% c(21:29) ~ "often",
      soda %in% c(30) ~ "daily",
      soda %in% c(31:max(soda)) ~ "daily+",
      TRUE ~ NA_character_)) %>%
  mutate(soda.cat = factor(soda.cat,
                     levels = c("never","rarely","sometimes","regularly",
                                "often","daily","daily+")))

ggplot(nhis22, aes(x = soda.cat, fill = gender)) +
  geom_bar(position = "dodge") +
  labs(title = "Bar Chart of Soda Consumption by Gender",
       x = "Soda",
       y = "Freq.",
       fill = "Gender") +
  scale_fill_manual(values = c("lightblue", "lightpink")) +
  theme_minimal()

ggplot(nhis22, aes(x = coffee.cat, fill = educ)) +
  geom_bar(position = "dodge") +
  labs(title = "Bar Chart of Coffee Consumption by Education",
       x = "Soda",
       y = "Freq.",
       fill = "Education") +
  scale_fill_manual(values = c("lightblue", "lightpink", "lightgreen", "purple")) +
  theme_minimal()

```

5. 

```{r task2_5, echo=FALSE}

library(ggcorrplot)

nhis22_cd <- nhis22[c("soda", "fruit_juice_pure","coffee", "sports_drink",
                         "fruit_juice_sweet","fruit","salad","fries","potato",
                         "beans","veggie","salsa","pizza","tomato_sauce")]

corr.table <- cor(nhis22_cd, use="complete.obs")

ggcorrplot(corr.table,method = "square", type = "lower",lab=TRUE,hc.order=TRUE)
      
```

6.

```{r task5_6, echo=FALSE}

#pizza
Q1p <- quantile(nhis22$pizza, 0.25)
Q3p <- quantile(nhis22$pizza, 0.75)
IQRp <- Q3p - Q1p
lower_bound_pizza <- Q1p - 1.5 * IQRp
upper_bound_pizza <- Q3p + 1.5 * IQRp

nhis22$pizza_outliers <- ifelse(nhis22$pizza < lower_bound_pizza | nhis22$pizza > upper_bound_pizza, TRUE, FALSE)

#salsa
Q1s <- quantile(nhis22$salsa, 0.25)
Q3s <- quantile(nhis22$salsa, 0.75)
IQRs <- Q3s - Q1s
lower_bound_salsa <- Q1s - 1.5 * IQRs
upper_bound_salsa <- Q3s + 1.5 * IQRs

nhis22$salsa_outliers <- ifelse(nhis22$salsa < lower_bound_salsa | nhis22$salsa > upper_bound_salsa, TRUE, FALSE)

#tomato sauce
Q1t <- quantile(nhis22$tomato_sauce, 0.25)
Q3t <- quantile(nhis22$tomato_sauce, 0.75)
IQRt <- Q3t - Q1t
lower_bound_tomsau <- Q1t - 1.5 * IQRt
upper_bound_tomsau <- Q3t + 1.5 * IQRt

nhis22$tomsau_outliers <- ifelse(nhis22$tomato_sauce < lower_bound_tomsau | nhis22$tomato_sauce > upper_bound_tomsau, TRUE, FALSE)

```

